config/routes.rb
MagnetPoetry::Application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, :words, :poem_words
  resources :poems do
    member do
      post 'spawn_new_words'
      post 'submit'
    end
  end
  resources :games do
    resources :votes
    member do
      get 'winner'
      get 'check_submissions'
    end
  end


  root to: 'static_pages#home'

  get 'signup', to: redirect("/users/sign_up")
  get 'signin', to: redirect("/users/sign_in")

  get "static_pages/about"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="masthead">
  <div class="row main-container">
    <div class="twelve columns centered masthead-content">
      <h1>Magnets!</h1>
      <p>Here's some hella sweet fake text talking about how cool this app is. It doesn't even exist yet, but I can assure you, it will be fully radical. So let me tell you some more about this app. It will be epic. it will be amazing. it will be mind blowing. You will love it in its entirety.</p>
      <% if !user_signed_in? %>
        <%= link_to "Join!", signup_path, class: "button large radius join-button" %>
      <% else %>
        <%= link_to "Play!", poems_path, method: :post, class: "button large radius join-button" %>
      <% end %>
      <div class="masthead-reviews row">
        <div class="review four columns">
          <p>s pattern splits the view (also called the presentation) into “dumb” templates that are primarily responsible for inserting pre-built data in between HTML tags. The model che business logic and knows how</p>
        </div>

        <div class="review four columns">
          <p>First area to check is the application log files. Have “tail -f” commands running on the server.log and development.log. Rails </p>
        </div>

        <div class="review four columns">
          <p>bugger support is available through the debugger command when you start your Mongrel or WEBrick server with –debugger. This means that you can break out of executione execution! You need to install ruby-debug to r</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="home-content">
  <div class="row main-container">
    <div class="twelve columns centered masthead-content">
      <h1>Magnets!</h1>
      <p>We have written example text for over 40 industry sectors, this is an ongoing project and we will be adding more copy if there is a demand so don’t hesitate to get in touch if you see a gap in our industry list. Please note though, that this copy is only designed for use at the concept stage and is not for use on live websites. If you are looking for a copywriter, we do that too so get in touch.</p>
      <%= link_to "Join!", signup_path, class: "button large radius join-button" %>
      <div class="masthead-reviews row">
        <div class="review four columns">
          <p><strong>OMG</strong><p>
          <p>s pattern splits the view (also called the presentation) into “dumb” templates that are primarily responsible for inserting pre-built data in between HTML tags. The model che business logic and knows how</p>
        </div>

        <div class="review four columns">
          <p><strong>People Really!</strong><p>
          <p>First area to check is the application log files. Have “tail -f” commands running on the server.log and development.log. Rails </p>
        </div>

        <div class="review four columns">
          <p><strong>Love us!</strong><p>
          <p>bugger support is available through the debugger command when you start your Mongrel or WEBrick server with –debugger. This means that you can break out of executione execution! You need to install ruby-debug to r</p>
        </div>
      </div>
    </div>
  </div>
</div>