config/routes.rb
MagnetPoetry::Application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, :words, :poem_words
  resources :poems do
    member do
      post 'spawn_new_words'
      post 'submit'
    end
  end
  resources :games do
    resources :votes
    member do
      get 'winner'
      get 'check_submissions'
    end
  end


  root to: 'static_pages#home'

  get 'signup', to: redirect("/users/sign_up")
  get 'signin', to: redirect("/users/sign_in")

  get "static_pages/about"
end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name, :user_id, :round_limit, :players_attributes, :user_ids

  has_many :rounds
  has_many :players, inverse_of: :game
  accepts_nested_attributes_for :players
  has_many :poems, through: :rounds
  has_many :users, through: :players

  # maybe crazy
  belongs_to :user

  def start_game
    round = self.rounds.build
    self.save
    Poem.create_player_poems(players, round.id)
    RoundPrompt.generate_random(round.id)
    self
  end

  def player_by_user_id(user_id)
    self.players.where(user_id: user_id)[0]
  end

  #this might actually be a helper
  def current_round
    self.rounds.last
  end

  def over?
    if self.current_round.round_number >= self.round_limit && self.current_round.all_voted?
      return true
    else
      return false
    end
  end

  def get_winner

  end

  def new_round
    round = Round.create(
      game_id: self.id,
      round_number: current_round.round_number + 1
    )

    Poem.create_player_poems(self.players, round.id)
    RoundPrompt.generate_random(round.id)
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @game = Game.new
    @users = User.where('id not in (?)', current_user.id )
    @game.players.build
  end

  def create
    game = Game.new(params[:game])
    user_ids = params[:game][:user_ids] << current_user.id
    game.user_ids = user_ids
    game.user_id = current_user.id
    if game.save
      game.start_game
      redirect_to game
    else
      render 'new'
    end
  end

  def show
    @game = Game.find(params[:id])
    @user = current_user

    @player_poem = Poem
      .joins("JOIN rounds ON rounds.id = poems.round_id")
      .where("rounds.game_id = ? AND
              poems.user_id = ? AND
              rounds.round_number = ?",
              params[:id], current_user.id,
              @game.current_round.round_number)
      .last

    @poem_words = @player_poem.poem_words
    @current_round = @game.current_round

    @current_prompt = @current_round.prompt

    if @game.over?
      redirect_to winner_game_path(@game)
    elsif @current_round.all_submitted? && !@current_round.user_voted?(@user)
      redirect_to new_game_vote_path(@game.id)
    end
  end

  def index

  end

  def winner
    @game = Game.find(params[:id])
    unless @game.over?
      redirect_to @game
    end
  end

  def check_submissions
    @game = Game.find(params[:id])
    submitted = @game.current_round.all_submitted?
    voted = @game.current_round.all_voted?
    hash = { submitted: submitted, voted: voted }
    respond_to do |format|
      format.json { render json: hash }
    end
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="masthead">
  <div class="row main-container">
    <div class="twelve columns centered masthead-content">
      <h1>New Game</h1>
      <%= simple_form_for @game do |f| %>
        <%= f.input :name %>
        <%= f.input :round_limit, collection: 5..20 %>
        <%= f.hidden_field :user_id, :value => current_user.id %>

        <%= f.input :user_ids,
                    collection: @users,
                    label_method: :username,
                    value_method: :id,
                    as: :check_boxes
         %>

        <%= f.submit "play!", class: "button large radius" %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="masthead">
  <div class="row main-container">
    <div class="twelve columns centered masthead-content">

      <h1><%= @game.name %></h1>
      <div class="row">
        <%= render "layouts/player_score_table" %>
        <div class="game-info">
          <h4 class="subheader">Game Round: <%= @game.current_round.round_number %></h4>
          <h5 class="subheader">Rounds Left: <%= @game.round_limit - @game.current_round.round_number %>
          <h5 class="subheader">Game Creator: <%= link_to @game.user.username, @game.user %></h5>
        </div>
        <div class="prompt">
          <h3>The Prompt:</h3>
          <h4 class="subheader"><%= @current_round.prompt.body %></h4>
        </div>
      </div>




      <% if !@player_poem.game_played %>

      <h3>Play your turn</h3>
      <%= render "layouts/magnets", container: "player-container", poem: @player_poem %>
        <%= button_to "submit this poem", submit_poem_path(@player_poem), method: :post, form_class: "add-more", class: "give-me-more button large radius" %>


      <% else %>
        <% if !@current_round.all_submitted? %>
          <h3>Waiting on everyone's move..</h3>
          <%= image_tag("horse.gif") %>
          <script>
            $(function(){
              setInterval(function(){
                $.getJSON('<%= @game.id %>/check_submissions.json', function(data){
                  console.log(data["submitted"])
                  if (data["submitted"] === true) {
                    location.reload()
                  }
                });
              }, 1000)
            });
          </script>
        <% elsif @current_round.all_submitted? && !@current_round.user_voted?(@user) %>
          <%= link_to "vote, yo", new_game_vote_path(@game.id), class: "button large radius" %>
        <% elsif @current_round.all_submitted? && @current_round.user_voted?(@user) %>
          <h3>Waiting on everyone's vote..</h3>
          <%= image_tag("horse.gif") %>
          <script>
            $(function(){
              setInterval(function(){
                $.getJSON('<%= @game.id %>/check_submissions.json', function(data){
                  console.log(data["voted"])
                  if (data["voted"] === false && data["submitted"] == false ) {
                    location.reload()
                  }
                });
              }, 1000)
            });
          </script>
        <% end %>
      <% end %>


      <pre>
      Todo list:
      PROBLEM -- TIES GO TO THE FIRST PERSON SELECTED
      add tiebreaker
      </pre>

    </div>
  </div>
</div>

app/views/games/vote.html.erb
<div class="masthead">
  <div class="row main-container">
    <div class="twelve columns centered masthead-content">

      <h1><%= @game.name %> Vote!</h1>
      <div class="row">
        <%= render "player_score_table" %>
        <div class="game-info">
          <h4 class="subheader">Game Round: <%= @game.current_round.round_number %></h4>
          <h5 class="subheader">Rounds Left: <%= @game.round_limit - @game.current_round.round_number %>
          <h5 class="subheader">Game Creator: <%= link_to @game.user.username, @game.user %></h5>
        </div>
        <div class="prompt">
          <h3>The Prompt:</h3>
          <h4 class="subheader"><%= @current_round.prompt.body %></h4>
        </div>
      </div>

      <% @poems.each do |poem| %>
        <%= render "poem_votes", container: "#{poem.id}-container", poem: poem %>
      <% end %>

    </div>
  </div>
</div>

app/views/games/winner.html.erb
Winnerz