config/routes.rb
MagnetPoetry::Application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, :words, :poem_words
  resources :poems do
    member do
      post 'spawn_new_words'
      post 'submit'
    end
  end
  resources :games do
    resources :votes
    member do
      get 'winner'
      get 'check_submissions'
    end
  end


  root to: 'static_pages#home'

  get 'signup', to: redirect("/users/sign_up")
  get 'signin', to: redirect("/users/sign_in")

  get "static_pages/about"
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="top-footer row">
    <div class="twelve columns">
      <div class="footer-links row">
        <div class="two columns top-footer-links">
          <p><strong>Magnets</strong><p>
          <ul>
            <li><%= link_to "random", "#" %></li>
            <li><%= link_to "foo bar", "#" %></li>
            <li><%= link_to "bars of foo", "#" %></li>
          </ul>
        </div>

        <div class="two columns top-footer-links">
          <p><strong>Magnets</strong><p>
          <ul>
            <li><%= link_to "strings eat", "#" %></li>
            <li><%= link_to "eat more", "#" %></li>
            <li><%= link_to "jellyfish", "#" %></li>
          </ul>
        </div>

        <div class="two columns top-footer-links">
          <p><strong>Magnets</strong><p>
          <ul>
            <li><%= link_to "peepsss", "#" %></li>
            <li><%= link_to "random", "#" %></li>
            <li><%= link_to "pepsi cola", "#" %></li>
          </ul>
        </div>

        <div class="four columns social-footer">
          <p><strong>Like Magnets? Share it with your friends!</strong></p>
          <h4><a href="#">Facebook</a></h4>
          <h4><a href="#">Twitter</a></h4>
          <h4><a href="#">Reddit</a></h4>
        </div>
      </div>
    </div>
  </div>

  <div class="sub-footer">
    <div class="row">
      <div class="twelve columns">
        <p class="muted">
          <strong>All the fun and obscenity of magnet poetry, now with your friends!</strong>
        <br>
        © Sean Woojin Kim 2012.
        </p>
      </div>
    </div>
  </div>

</footer>

app/views/layouts/_magnets.html.erb
<div class="magnets-container">
  <div class="row">
    <div class="magnets eleven columns centered <%= container %>">
    </div>
  </div>
  <%= button_to "These words are inadequate! I need more!", spawn_new_words_poem_path(poem), method: :post, remote: true, form_class: "add-more", class: "give-me-more button large radius" %>
</div>

<script>
  var magnetData = <%= poem.poem_words.to_json.html_safe %>;

  $(function(){
    magnet = new Magnet.Controller(magnetData, "<%= ".#{container}" %>");
    magnet.start();

  });
</script>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <ul>
    <li class="name"><h1><%= link_to "Magnets", root_path %></h1></li>
    <li class="toggle-topbar"><a href="#"></a></li>
  </ul>
  <section>
    <ul class="right">
        <li><a href="#" class="debug-toggle">debug-mode</a></li>
      <% if !user_signed_in? %>
        <li><%= link_to "Login", signin_path %></li>
      <% else %>
        <li class="has-dropdown">
          <a href="#">Menu</a>
          <ul class="dropdown">
            <% if current_user.players.last != nil %>
              <li><%= link_to "My Latest Game", current_user.players.last.game %></li>
            <% end %>
            <li><%= link_to "New Game", new_game_path, method: :get %>
            <li><%= link_to "New Poem", poems_path, method: :post %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/_player_score_table.html.erb

  <div class="player-points game-info">
    <table>
      <caption>Scoreboard</caption>
      <thead>
        <tr>
          <th>Player</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
      <% @game.players.each do |player| %>
        <tr>
          <td><%= link_to player.user.username, player.user %></td>
          <td><%= player.points %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div>

app/views/layouts/_poem_votes.html.erb
<div class="magnets-container">
  <div class="row">
    <div class="magnets eleven columns centered <%= container %>">
    </div>
  </div>
  <%= button_to "I choose you!",
                game_votes_path(
                  user_id: current_user.id,
                  poem_id: poem.id,
                  game_id: @game.id
                ),
                method: :post,
                form_class: "add-more",
                class: "give-me-more button large radius" %>
</div>
<%= poem.id %>

<script>
  var magnetData<%= poem.id %> = <%= poem.poem_words.to_json.html_safe %>;

  $(function(){
    magnet<%= poem.id %> = new Magnet.Controller(magnetData<%= poem.id %>, "<%= ".#{container}" %>");
    magnet<%= poem.id %>.start();

  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!-- google web fonts -->
  <link href='http://fonts.googleapis.com/css?family=Sanchez' rel='stylesheet' type='text/css'>
</head>
<body>
	<%= render "layouts/nav" %>
  <% if notice || alert %>
    <div class="alert-box no-margin">
      <%= notice %>
      <%= alert %>
      <a href="" class="close">&times;</a>
    </div>
  <% end %>

  <%= yield %>

  <% if Rails.env.development? %>
  <div class="debug" style="padding: 10px; background: red; color: white;">
    <div class="row">
      <div class="twelve columns">
        DEBUG INFO
        <%= debug(params) %>
      </div>
    </div>
  </div>
  <% end %>


	<%= render "layouts/footer" %>
</body>
</html>